server:
  port: 5000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
        routes:
          - id: TASK-USER-SERVICE
            uri:
              lb://TASK-USER-SERVICE
            predicates:
              - Path=/auth/**, /api/users/**, /users/**

          - id: TASK-SERVICE
            uri:
              lb://TASK-SERVICE
            predicates:
              - Path=/api/tasks/**, /tasks/**

          - id: TASK-SUBMISSION-SERVICE
            uri:
              lb://TASK-SUBMISSION-SERVICE
            predicates:
              - Path=/api/submissions/**, /submissions/**

        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        global-cors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/